export const story = [
  { 
    period: '2009 – 2010', 
    institution: 'Centro Paula Souza - Etec São Roque', 
    position: 'Tecnologia da Informação',
    description: 'Técnico em Informática',
    location: 'São Roque-SP, Brasil',
    icon: 'Education',
  },
  { 
    period: '2014 – 2016', 
    institution: 'Fatec São Roque', 
    position: 'Tecnologia da Informação',
    description: 'Sistema para Internet',
    location: 'São Roque-SP, Brasil',
    icon: 'Education',
  },
  { 
    period: '2012 – 05/2016', 
    institution: 'Secretaria da Educação do Estado de São Paulo', 
    position: 'Agente Organização Escolar',
    description: 'Minhas responsabilidades sempre foram cuidar do patrimônio público, estabelecer o contato entre os estudantes e a gestão da escola, resolver os conflitos entre professores e alunos.',
    location: 'Ibíuna-SP, Brasil',
    icon: 'Work',
  },
  { 
    period: '11/2015 – 05/2016', 
    institution: 'SRTI - São Roque Tecnologia da Informação', 
    position: 'Estagiário',
    description: 'Trabalhei no desenvolvimento de aplicações web, sites responsivos, trabalhei principalmente com desenvolvimento front-end.',
    location: 'São Roque-SP, Brasil',
    icon: 'Work',
  },
  { 
    period: '2016 – 09/2017', 
    institution: 'Novacia', 
    position: 'Assistente Web',
    description: 'Auxiliando no desenvolvimento de e-mail marketing e sites funcionais, responsivos, sob medida para nossos clientes.',
    location: 'São Paulo, Brasil',
    icon: 'Work',
  },
  { 
    period: '2017 – 09/2019', 
    institution: 'Atitude Mídia Digital', 
    position: 'Desenvolvedor Web',
    description: 'Trabalhei desenvolvendo produtos e soluções internas para empresa e externas, atualizando os produtos que já existiam.',
    location: 'São Paulo, Brasil',
    icon: 'Work',
  },
  { 
    period: `2019 – ${new Date().getFullYear()}`, 
    institution: 'FDTE - Fundação para o Desenvolvimento Tecnológico da Engenharia', 
    position: 'Desenvolvedor Web Pleno',
    description: 'Trabalho como consultor, em projetos, sendo desenvolvedor Full-Stack, assim fazendo parte da força de trabalho destes clientes, assim nos projetos, construindo features, bugfixes, refatorando e reconstruindo quando necessário.',
    location: 'São Paulo, Brasil',
    icon: 'Work',
  }
]